### ISSUE TITLE
Deploy UI on Heroku

### ISSUE THREAD

**Issue by digitalfishpond** [NephologyFJ/nephology-ui#3]
[DoD] the UI can communicate with the back end when both are running in Heroku.

**Comment by victorhrsilva** [comment]
Resolved by pre-compiling Angular code to static files post npm install and set a static node.js server to handle the access to the static files.
Commit [dc8227e](https://github.com/NephologyFJ/nephology-ui/commit/dc8227e337b895c577f78fb647bbb436e0daed27)
